// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: DescriptorIndex.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_DescriptorIndex_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_DescriptorIndex_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3020000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3020000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/message_lite.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_DescriptorIndex_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_DescriptorIndex_2eproto {
  static const uint32_t offsets[];
};
namespace DescriptorIndex {
class DescriptorIndex;
struct DescriptorIndexDefaultTypeInternal;
extern DescriptorIndexDefaultTypeInternal _DescriptorIndex_default_instance_;
class FileEntry;
struct FileEntryDefaultTypeInternal;
extern FileEntryDefaultTypeInternal _FileEntry_default_instance_;
class Package;
struct PackageDefaultTypeInternal;
extern PackageDefaultTypeInternal _Package_default_instance_;
class Symbol;
struct SymbolDefaultTypeInternal;
extern SymbolDefaultTypeInternal _Symbol_default_instance_;
}  // namespace DescriptorIndex
PROTOBUF_NAMESPACE_OPEN
template<> ::DescriptorIndex::DescriptorIndex* Arena::CreateMaybeMessage<::DescriptorIndex::DescriptorIndex>(Arena*);
template<> ::DescriptorIndex::FileEntry* Arena::CreateMaybeMessage<::DescriptorIndex::FileEntry>(Arena*);
template<> ::DescriptorIndex::Package* Arena::CreateMaybeMessage<::DescriptorIndex::Package>(Arena*);
template<> ::DescriptorIndex::Symbol* Arena::CreateMaybeMessage<::DescriptorIndex::Symbol>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace DescriptorIndex {

// ===================================================================

class FileEntry final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:DescriptorIndex.FileEntry) */ {
 public:
  inline FileEntry() : FileEntry(nullptr) {}
  ~FileEntry() override;
  explicit PROTOBUF_CONSTEXPR FileEntry(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  FileEntry(const FileEntry& from);
  FileEntry(FileEntry&& from) noexcept
    : FileEntry() {
    *this = ::std::move(from);
  }

  inline FileEntry& operator=(const FileEntry& from) {
    CopyFrom(from);
    return *this;
  }
  inline FileEntry& operator=(FileEntry&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const FileEntry& default_instance() {
    return *internal_default_instance();
  }
  static inline const FileEntry* internal_default_instance() {
    return reinterpret_cast<const FileEntry*>(
               &_FileEntry_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(FileEntry& a, FileEntry& b) {
    a.Swap(&b);
  }
  inline void Swap(FileEntry* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(FileEntry* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  FileEntry* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<FileEntry>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const FileEntry& from);
  void MergeFrom(const FileEntry& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(FileEntry* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "DescriptorIndex.FileEntry";
  }
  protected:
  explicit FileEntry(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFileNameFieldNumber = 1,
    kDataOffsetFieldNumber = 2,
    kLengthFieldNumber = 3,
  };
  // string file_name = 1;
  void clear_file_name();
  const std::string& file_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_file_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_file_name();
  PROTOBUF_NODISCARD std::string* release_file_name();
  void set_allocated_file_name(std::string* file_name);
  private:
  const std::string& _internal_file_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_file_name(const std::string& value);
  std::string* _internal_mutable_file_name();
  public:

  // uint64 data_offset = 2;
  void clear_data_offset();
  uint64_t data_offset() const;
  void set_data_offset(uint64_t value);
  private:
  uint64_t _internal_data_offset() const;
  void _internal_set_data_offset(uint64_t value);
  public:

  // uint32 length = 3;
  void clear_length();
  uint32_t length() const;
  void set_length(uint32_t value);
  private:
  uint32_t _internal_length() const;
  void _internal_set_length(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:DescriptorIndex.FileEntry)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr file_name_;
  uint64_t data_offset_;
  uint32_t length_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_DescriptorIndex_2eproto;
};
// -------------------------------------------------------------------

class Symbol final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:DescriptorIndex.Symbol) */ {
 public:
  inline Symbol() : Symbol(nullptr) {}
  ~Symbol() override;
  explicit PROTOBUF_CONSTEXPR Symbol(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Symbol(const Symbol& from);
  Symbol(Symbol&& from) noexcept
    : Symbol() {
    *this = ::std::move(from);
  }

  inline Symbol& operator=(const Symbol& from) {
    CopyFrom(from);
    return *this;
  }
  inline Symbol& operator=(Symbol&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Symbol& default_instance() {
    return *internal_default_instance();
  }
  static inline const Symbol* internal_default_instance() {
    return reinterpret_cast<const Symbol*>(
               &_Symbol_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Symbol& a, Symbol& b) {
    a.Swap(&b);
  }
  inline void Swap(Symbol* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Symbol* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Symbol* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Symbol>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Symbol& from);
  void MergeFrom(const Symbol& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Symbol* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "DescriptorIndex.Symbol";
  }
  protected:
  explicit Symbol(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFullNameFieldNumber = 1,
    kFileIndexFieldNumber = 2,
  };
  // string full_name = 1;
  void clear_full_name();
  const std::string& full_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_full_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_full_name();
  PROTOBUF_NODISCARD std::string* release_full_name();
  void set_allocated_full_name(std::string* full_name);
  private:
  const std::string& _internal_full_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_full_name(const std::string& value);
  std::string* _internal_mutable_full_name();
  public:

  // uint32 file_index = 2;
  void clear_file_index();
  uint32_t file_index() const;
  void set_file_index(uint32_t value);
  private:
  uint32_t _internal_file_index() const;
  void _internal_set_file_index(uint32_t value);
  public:

  // @@protoc_insertion_point(class_scope:DescriptorIndex.Symbol)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr full_name_;
  uint32_t file_index_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_DescriptorIndex_2eproto;
};
// -------------------------------------------------------------------

class Package final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:DescriptorIndex.Package) */ {
 public:
  inline Package() : Package(nullptr) {}
  ~Package() override;
  explicit PROTOBUF_CONSTEXPR Package(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Package(const Package& from);
  Package(Package&& from) noexcept
    : Package() {
    *this = ::std::move(from);
  }

  inline Package& operator=(const Package& from) {
    CopyFrom(from);
    return *this;
  }
  inline Package& operator=(Package&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const Package& default_instance() {
    return *internal_default_instance();
  }
  static inline const Package* internal_default_instance() {
    return reinterpret_cast<const Package*>(
               &_Package_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(Package& a, Package& b) {
    a.Swap(&b);
  }
  inline void Swap(Package* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Package* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Package* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Package>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const Package& from);
  void MergeFrom(const Package& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Package* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "DescriptorIndex.Package";
  }
  protected:
  explicit Package(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSymbolIndexesFieldNumber = 2,
    kNestedPackageIndexesFieldNumber = 3,
    kFullNameFieldNumber = 1,
  };
  // repeated uint32 symbol_indexes = 2;
  int symbol_indexes_size() const;
  private:
  int _internal_symbol_indexes_size() const;
  public:
  void clear_symbol_indexes();
  private:
  uint32_t _internal_symbol_indexes(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
      _internal_symbol_indexes() const;
  void _internal_add_symbol_indexes(uint32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
      _internal_mutable_symbol_indexes();
  public:
  uint32_t symbol_indexes(int index) const;
  void set_symbol_indexes(int index, uint32_t value);
  void add_symbol_indexes(uint32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
      symbol_indexes() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
      mutable_symbol_indexes();

  // repeated uint32 nested_package_indexes = 3;
  int nested_package_indexes_size() const;
  private:
  int _internal_nested_package_indexes_size() const;
  public:
  void clear_nested_package_indexes();
  private:
  uint32_t _internal_nested_package_indexes(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
      _internal_nested_package_indexes() const;
  void _internal_add_nested_package_indexes(uint32_t value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
      _internal_mutable_nested_package_indexes();
  public:
  uint32_t nested_package_indexes(int index) const;
  void set_nested_package_indexes(int index, uint32_t value);
  void add_nested_package_indexes(uint32_t value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
      nested_package_indexes() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
      mutable_nested_package_indexes();

  // string full_name = 1;
  void clear_full_name();
  const std::string& full_name() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_full_name(ArgT0&& arg0, ArgT... args);
  std::string* mutable_full_name();
  PROTOBUF_NODISCARD std::string* release_full_name();
  void set_allocated_full_name(std::string* full_name);
  private:
  const std::string& _internal_full_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_full_name(const std::string& value);
  std::string* _internal_mutable_full_name();
  public:

  // @@protoc_insertion_point(class_scope:DescriptorIndex.Package)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t > symbol_indexes_;
  mutable std::atomic<int> _symbol_indexes_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t > nested_package_indexes_;
  mutable std::atomic<int> _nested_package_indexes_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr full_name_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_DescriptorIndex_2eproto;
};
// -------------------------------------------------------------------

class DescriptorIndex final :
    public ::PROTOBUF_NAMESPACE_ID::MessageLite /* @@protoc_insertion_point(class_definition:DescriptorIndex.DescriptorIndex) */ {
 public:
  inline DescriptorIndex() : DescriptorIndex(nullptr) {}
  ~DescriptorIndex() override;
  explicit PROTOBUF_CONSTEXPR DescriptorIndex(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  DescriptorIndex(const DescriptorIndex& from);
  DescriptorIndex(DescriptorIndex&& from) noexcept
    : DescriptorIndex() {
    *this = ::std::move(from);
  }

  inline DescriptorIndex& operator=(const DescriptorIndex& from) {
    CopyFrom(from);
    return *this;
  }
  inline DescriptorIndex& operator=(DescriptorIndex&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const DescriptorIndex& default_instance() {
    return *internal_default_instance();
  }
  static inline const DescriptorIndex* internal_default_instance() {
    return reinterpret_cast<const DescriptorIndex*>(
               &_DescriptorIndex_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(DescriptorIndex& a, DescriptorIndex& b) {
    a.Swap(&b);
  }
  inline void Swap(DescriptorIndex* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(DescriptorIndex* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  DescriptorIndex* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<DescriptorIndex>(arena);
  }
  void CheckTypeAndMergeFrom(const ::PROTOBUF_NAMESPACE_ID::MessageLite& from)  final;
  void CopyFrom(const DescriptorIndex& from);
  void MergeFrom(const DescriptorIndex& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(DescriptorIndex* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "DescriptorIndex.DescriptorIndex";
  }
  protected:
  explicit DescriptorIndex(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  std::string GetTypeName() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFilesFieldNumber = 1,
    kSymbolsFieldNumber = 2,
    kPackagesFieldNumber = 3,
  };
  // repeated .DescriptorIndex.FileEntry files = 1;
  int files_size() const;
  private:
  int _internal_files_size() const;
  public:
  void clear_files();
  ::DescriptorIndex::FileEntry* mutable_files(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DescriptorIndex::FileEntry >*
      mutable_files();
  private:
  const ::DescriptorIndex::FileEntry& _internal_files(int index) const;
  ::DescriptorIndex::FileEntry* _internal_add_files();
  public:
  const ::DescriptorIndex::FileEntry& files(int index) const;
  ::DescriptorIndex::FileEntry* add_files();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DescriptorIndex::FileEntry >&
      files() const;

  // repeated .DescriptorIndex.Symbol symbols = 2;
  int symbols_size() const;
  private:
  int _internal_symbols_size() const;
  public:
  void clear_symbols();
  ::DescriptorIndex::Symbol* mutable_symbols(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DescriptorIndex::Symbol >*
      mutable_symbols();
  private:
  const ::DescriptorIndex::Symbol& _internal_symbols(int index) const;
  ::DescriptorIndex::Symbol* _internal_add_symbols();
  public:
  const ::DescriptorIndex::Symbol& symbols(int index) const;
  ::DescriptorIndex::Symbol* add_symbols();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DescriptorIndex::Symbol >&
      symbols() const;

  // repeated .DescriptorIndex.Package packages = 3;
  int packages_size() const;
  private:
  int _internal_packages_size() const;
  public:
  void clear_packages();
  ::DescriptorIndex::Package* mutable_packages(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DescriptorIndex::Package >*
      mutable_packages();
  private:
  const ::DescriptorIndex::Package& _internal_packages(int index) const;
  ::DescriptorIndex::Package* _internal_add_packages();
  public:
  const ::DescriptorIndex::Package& packages(int index) const;
  ::DescriptorIndex::Package* add_packages();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DescriptorIndex::Package >&
      packages() const;

  // @@protoc_insertion_point(class_scope:DescriptorIndex.DescriptorIndex)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DescriptorIndex::FileEntry > files_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DescriptorIndex::Symbol > symbols_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DescriptorIndex::Package > packages_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_DescriptorIndex_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// FileEntry

// string file_name = 1;
inline void FileEntry::clear_file_name() {
  file_name_.ClearToEmpty();
}
inline const std::string& FileEntry::file_name() const {
  // @@protoc_insertion_point(field_get:DescriptorIndex.FileEntry.file_name)
  return _internal_file_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void FileEntry::set_file_name(ArgT0&& arg0, ArgT... args) {
 
 file_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:DescriptorIndex.FileEntry.file_name)
}
inline std::string* FileEntry::mutable_file_name() {
  std::string* _s = _internal_mutable_file_name();
  // @@protoc_insertion_point(field_mutable:DescriptorIndex.FileEntry.file_name)
  return _s;
}
inline const std::string& FileEntry::_internal_file_name() const {
  return file_name_.Get();
}
inline void FileEntry::_internal_set_file_name(const std::string& value) {
  
  file_name_.Set(value, GetArenaForAllocation());
}
inline std::string* FileEntry::_internal_mutable_file_name() {
  
  return file_name_.Mutable(GetArenaForAllocation());
}
inline std::string* FileEntry::release_file_name() {
  // @@protoc_insertion_point(field_release:DescriptorIndex.FileEntry.file_name)
  return file_name_.Release();
}
inline void FileEntry::set_allocated_file_name(std::string* file_name) {
  if (file_name != nullptr) {
    
  } else {
    
  }
  file_name_.SetAllocated(file_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (file_name_.IsDefault()) {
    file_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:DescriptorIndex.FileEntry.file_name)
}

// uint64 data_offset = 2;
inline void FileEntry::clear_data_offset() {
  data_offset_ = uint64_t{0u};
}
inline uint64_t FileEntry::_internal_data_offset() const {
  return data_offset_;
}
inline uint64_t FileEntry::data_offset() const {
  // @@protoc_insertion_point(field_get:DescriptorIndex.FileEntry.data_offset)
  return _internal_data_offset();
}
inline void FileEntry::_internal_set_data_offset(uint64_t value) {
  
  data_offset_ = value;
}
inline void FileEntry::set_data_offset(uint64_t value) {
  _internal_set_data_offset(value);
  // @@protoc_insertion_point(field_set:DescriptorIndex.FileEntry.data_offset)
}

// uint32 length = 3;
inline void FileEntry::clear_length() {
  length_ = 0u;
}
inline uint32_t FileEntry::_internal_length() const {
  return length_;
}
inline uint32_t FileEntry::length() const {
  // @@protoc_insertion_point(field_get:DescriptorIndex.FileEntry.length)
  return _internal_length();
}
inline void FileEntry::_internal_set_length(uint32_t value) {
  
  length_ = value;
}
inline void FileEntry::set_length(uint32_t value) {
  _internal_set_length(value);
  // @@protoc_insertion_point(field_set:DescriptorIndex.FileEntry.length)
}

// -------------------------------------------------------------------

// Symbol

// string full_name = 1;
inline void Symbol::clear_full_name() {
  full_name_.ClearToEmpty();
}
inline const std::string& Symbol::full_name() const {
  // @@protoc_insertion_point(field_get:DescriptorIndex.Symbol.full_name)
  return _internal_full_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Symbol::set_full_name(ArgT0&& arg0, ArgT... args) {
 
 full_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:DescriptorIndex.Symbol.full_name)
}
inline std::string* Symbol::mutable_full_name() {
  std::string* _s = _internal_mutable_full_name();
  // @@protoc_insertion_point(field_mutable:DescriptorIndex.Symbol.full_name)
  return _s;
}
inline const std::string& Symbol::_internal_full_name() const {
  return full_name_.Get();
}
inline void Symbol::_internal_set_full_name(const std::string& value) {
  
  full_name_.Set(value, GetArenaForAllocation());
}
inline std::string* Symbol::_internal_mutable_full_name() {
  
  return full_name_.Mutable(GetArenaForAllocation());
}
inline std::string* Symbol::release_full_name() {
  // @@protoc_insertion_point(field_release:DescriptorIndex.Symbol.full_name)
  return full_name_.Release();
}
inline void Symbol::set_allocated_full_name(std::string* full_name) {
  if (full_name != nullptr) {
    
  } else {
    
  }
  full_name_.SetAllocated(full_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (full_name_.IsDefault()) {
    full_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:DescriptorIndex.Symbol.full_name)
}

// uint32 file_index = 2;
inline void Symbol::clear_file_index() {
  file_index_ = 0u;
}
inline uint32_t Symbol::_internal_file_index() const {
  return file_index_;
}
inline uint32_t Symbol::file_index() const {
  // @@protoc_insertion_point(field_get:DescriptorIndex.Symbol.file_index)
  return _internal_file_index();
}
inline void Symbol::_internal_set_file_index(uint32_t value) {
  
  file_index_ = value;
}
inline void Symbol::set_file_index(uint32_t value) {
  _internal_set_file_index(value);
  // @@protoc_insertion_point(field_set:DescriptorIndex.Symbol.file_index)
}

// -------------------------------------------------------------------

// Package

// string full_name = 1;
inline void Package::clear_full_name() {
  full_name_.ClearToEmpty();
}
inline const std::string& Package::full_name() const {
  // @@protoc_insertion_point(field_get:DescriptorIndex.Package.full_name)
  return _internal_full_name();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Package::set_full_name(ArgT0&& arg0, ArgT... args) {
 
 full_name_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:DescriptorIndex.Package.full_name)
}
inline std::string* Package::mutable_full_name() {
  std::string* _s = _internal_mutable_full_name();
  // @@protoc_insertion_point(field_mutable:DescriptorIndex.Package.full_name)
  return _s;
}
inline const std::string& Package::_internal_full_name() const {
  return full_name_.Get();
}
inline void Package::_internal_set_full_name(const std::string& value) {
  
  full_name_.Set(value, GetArenaForAllocation());
}
inline std::string* Package::_internal_mutable_full_name() {
  
  return full_name_.Mutable(GetArenaForAllocation());
}
inline std::string* Package::release_full_name() {
  // @@protoc_insertion_point(field_release:DescriptorIndex.Package.full_name)
  return full_name_.Release();
}
inline void Package::set_allocated_full_name(std::string* full_name) {
  if (full_name != nullptr) {
    
  } else {
    
  }
  full_name_.SetAllocated(full_name, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (full_name_.IsDefault()) {
    full_name_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:DescriptorIndex.Package.full_name)
}

// repeated uint32 symbol_indexes = 2;
inline int Package::_internal_symbol_indexes_size() const {
  return symbol_indexes_.size();
}
inline int Package::symbol_indexes_size() const {
  return _internal_symbol_indexes_size();
}
inline void Package::clear_symbol_indexes() {
  symbol_indexes_.Clear();
}
inline uint32_t Package::_internal_symbol_indexes(int index) const {
  return symbol_indexes_.Get(index);
}
inline uint32_t Package::symbol_indexes(int index) const {
  // @@protoc_insertion_point(field_get:DescriptorIndex.Package.symbol_indexes)
  return _internal_symbol_indexes(index);
}
inline void Package::set_symbol_indexes(int index, uint32_t value) {
  symbol_indexes_.Set(index, value);
  // @@protoc_insertion_point(field_set:DescriptorIndex.Package.symbol_indexes)
}
inline void Package::_internal_add_symbol_indexes(uint32_t value) {
  symbol_indexes_.Add(value);
}
inline void Package::add_symbol_indexes(uint32_t value) {
  _internal_add_symbol_indexes(value);
  // @@protoc_insertion_point(field_add:DescriptorIndex.Package.symbol_indexes)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
Package::_internal_symbol_indexes() const {
  return symbol_indexes_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
Package::symbol_indexes() const {
  // @@protoc_insertion_point(field_list:DescriptorIndex.Package.symbol_indexes)
  return _internal_symbol_indexes();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
Package::_internal_mutable_symbol_indexes() {
  return &symbol_indexes_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
Package::mutable_symbol_indexes() {
  // @@protoc_insertion_point(field_mutable_list:DescriptorIndex.Package.symbol_indexes)
  return _internal_mutable_symbol_indexes();
}

// repeated uint32 nested_package_indexes = 3;
inline int Package::_internal_nested_package_indexes_size() const {
  return nested_package_indexes_.size();
}
inline int Package::nested_package_indexes_size() const {
  return _internal_nested_package_indexes_size();
}
inline void Package::clear_nested_package_indexes() {
  nested_package_indexes_.Clear();
}
inline uint32_t Package::_internal_nested_package_indexes(int index) const {
  return nested_package_indexes_.Get(index);
}
inline uint32_t Package::nested_package_indexes(int index) const {
  // @@protoc_insertion_point(field_get:DescriptorIndex.Package.nested_package_indexes)
  return _internal_nested_package_indexes(index);
}
inline void Package::set_nested_package_indexes(int index, uint32_t value) {
  nested_package_indexes_.Set(index, value);
  // @@protoc_insertion_point(field_set:DescriptorIndex.Package.nested_package_indexes)
}
inline void Package::_internal_add_nested_package_indexes(uint32_t value) {
  nested_package_indexes_.Add(value);
}
inline void Package::add_nested_package_indexes(uint32_t value) {
  _internal_add_nested_package_indexes(value);
  // @@protoc_insertion_point(field_add:DescriptorIndex.Package.nested_package_indexes)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
Package::_internal_nested_package_indexes() const {
  return nested_package_indexes_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >&
Package::nested_package_indexes() const {
  // @@protoc_insertion_point(field_list:DescriptorIndex.Package.nested_package_indexes)
  return _internal_nested_package_indexes();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
Package::_internal_mutable_nested_package_indexes() {
  return &nested_package_indexes_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< uint32_t >*
Package::mutable_nested_package_indexes() {
  // @@protoc_insertion_point(field_mutable_list:DescriptorIndex.Package.nested_package_indexes)
  return _internal_mutable_nested_package_indexes();
}

// -------------------------------------------------------------------

// DescriptorIndex

// repeated .DescriptorIndex.FileEntry files = 1;
inline int DescriptorIndex::_internal_files_size() const {
  return files_.size();
}
inline int DescriptorIndex::files_size() const {
  return _internal_files_size();
}
inline void DescriptorIndex::clear_files() {
  files_.Clear();
}
inline ::DescriptorIndex::FileEntry* DescriptorIndex::mutable_files(int index) {
  // @@protoc_insertion_point(field_mutable:DescriptorIndex.DescriptorIndex.files)
  return files_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DescriptorIndex::FileEntry >*
DescriptorIndex::mutable_files() {
  // @@protoc_insertion_point(field_mutable_list:DescriptorIndex.DescriptorIndex.files)
  return &files_;
}
inline const ::DescriptorIndex::FileEntry& DescriptorIndex::_internal_files(int index) const {
  return files_.Get(index);
}
inline const ::DescriptorIndex::FileEntry& DescriptorIndex::files(int index) const {
  // @@protoc_insertion_point(field_get:DescriptorIndex.DescriptorIndex.files)
  return _internal_files(index);
}
inline ::DescriptorIndex::FileEntry* DescriptorIndex::_internal_add_files() {
  return files_.Add();
}
inline ::DescriptorIndex::FileEntry* DescriptorIndex::add_files() {
  ::DescriptorIndex::FileEntry* _add = _internal_add_files();
  // @@protoc_insertion_point(field_add:DescriptorIndex.DescriptorIndex.files)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DescriptorIndex::FileEntry >&
DescriptorIndex::files() const {
  // @@protoc_insertion_point(field_list:DescriptorIndex.DescriptorIndex.files)
  return files_;
}

// repeated .DescriptorIndex.Symbol symbols = 2;
inline int DescriptorIndex::_internal_symbols_size() const {
  return symbols_.size();
}
inline int DescriptorIndex::symbols_size() const {
  return _internal_symbols_size();
}
inline void DescriptorIndex::clear_symbols() {
  symbols_.Clear();
}
inline ::DescriptorIndex::Symbol* DescriptorIndex::mutable_symbols(int index) {
  // @@protoc_insertion_point(field_mutable:DescriptorIndex.DescriptorIndex.symbols)
  return symbols_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DescriptorIndex::Symbol >*
DescriptorIndex::mutable_symbols() {
  // @@protoc_insertion_point(field_mutable_list:DescriptorIndex.DescriptorIndex.symbols)
  return &symbols_;
}
inline const ::DescriptorIndex::Symbol& DescriptorIndex::_internal_symbols(int index) const {
  return symbols_.Get(index);
}
inline const ::DescriptorIndex::Symbol& DescriptorIndex::symbols(int index) const {
  // @@protoc_insertion_point(field_get:DescriptorIndex.DescriptorIndex.symbols)
  return _internal_symbols(index);
}
inline ::DescriptorIndex::Symbol* DescriptorIndex::_internal_add_symbols() {
  return symbols_.Add();
}
inline ::DescriptorIndex::Symbol* DescriptorIndex::add_symbols() {
  ::DescriptorIndex::Symbol* _add = _internal_add_symbols();
  // @@protoc_insertion_point(field_add:DescriptorIndex.DescriptorIndex.symbols)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DescriptorIndex::Symbol >&
DescriptorIndex::symbols() const {
  // @@protoc_insertion_point(field_list:DescriptorIndex.DescriptorIndex.symbols)
  return symbols_;
}

// repeated .DescriptorIndex.Package packages = 3;
inline int DescriptorIndex::_internal_packages_size() const {
  return packages_.size();
}
inline int DescriptorIndex::packages_size() const {
  return _internal_packages_size();
}
inline void DescriptorIndex::clear_packages() {
  packages_.Clear();
}
inline ::DescriptorIndex::Package* DescriptorIndex::mutable_packages(int index) {
  // @@protoc_insertion_point(field_mutable:DescriptorIndex.DescriptorIndex.packages)
  return packages_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DescriptorIndex::Package >*
DescriptorIndex::mutable_packages() {
  // @@protoc_insertion_point(field_mutable_list:DescriptorIndex.DescriptorIndex.packages)
  return &packages_;
}
inline const ::DescriptorIndex::Package& DescriptorIndex::_internal_packages(int index) const {
  return packages_.Get(index);
}
inline const ::DescriptorIndex::Package& DescriptorIndex::packages(int index) const {
  // @@protoc_insertion_point(field_get:DescriptorIndex.DescriptorIndex.packages)
  return _internal_packages(index);
}
inline ::DescriptorIndex::Package* DescriptorIndex::_internal_add_packages() {
  return packages_.Add();
}
inline ::DescriptorIndex::Package* DescriptorIndex::add_packages() {
  ::DescriptorIndex::Package* _add = _internal_add_packages();
  // @@protoc_insertion_point(field_add:DescriptorIndex.DescriptorIndex.packages)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::DescriptorIndex::Package >&
DescriptorIndex::packages() const {
  // @@protoc_insertion_point(field_list:DescriptorIndex.DescriptorIndex.packages)
  return packages_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace DescriptorIndex

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_DescriptorIndex_2eproto
